// Nội dung Podcast — bài nghe VOA Learning English (public domain, hợp pháp)
// Transcript EN lấy từ trang gốc VOA; phần dịch VI do chúng tôi biên soạn.
// Muốn thêm bài: copy 1 object mẫu, điền audioUrl (lấy nút "Direct link" trên trang
// episode của VOA) + en/vi transcript tương ứng.

export const YOUTUBE_CHANNELS = [
  {
    id: 'bbc-learning-english',
    name: 'BBC Learning English',
    handle: '@bbclearningenglish',
    url: 'https://www.youtube.com/@bbclearningenglish',
    description: 'Kênh chính thức BBC — 6 Minute English, The English We Speak, News Review.',
    color: '#7c0b0b',
  },
  {
    id: 'voa-learning-english',
    name: 'VOA Learning English',
    handle: '@VOALearningEnglish',
    url: 'https://www.youtube.com/@VOALearningEnglish',
    description: 'VOA — tin chậm, Words and Their Stories, Everyday Grammar TV.',
    color: '#0057b8',
  },
  {
    id: 'english-with-lucy',
    name: 'English with Lucy',
    handle: '@EnglishwithLucy',
    url: 'https://www.youtube.com/@EnglishwithLucy',
    description: 'Phát âm, từ vựng, ngữ pháp tiếng Anh thực dụng.',
    color: '#e8590c',
  },
  {
    id: 'ted-ed',
    name: 'TED-Ed',
    handle: '@TEDEd',
    url: 'https://www.youtube.com/@TEDEd',
    description: 'Video hoạt hình ngắn nhiều chủ đề — nghe hiểu học thuật.',
    color: '#e62b1e',
  },
  {
    id: 'rachels-english',
    name: "Rachel's English",
    handle: '@rachelsenglish',
    url: 'https://www.youtube.com/@rachelsenglish',
    description: 'Luyện phát âm Anh-Mỹ chậm, rõ, chi tiết.',
    color: '#ad1457',
  },
];

export const PODCAST_LESSONS = [
  {
    id: 'green-means-spring',
    title: 'Green Means Spring and Other Things',
    series: 'VOA Learning English — Words and Their Stories',
    date: '2025-03-07',
    level: 'Trung cấp',
    duration: '5:14',
    audioUrl: 'https://voa-audio.voanews.eu/vle/2025/03/06/323d1873-affa-4fac-2d98-08dd5c897904_hq.mp3',
    audioPageUrl: 'https://learningenglish.voanews.com/a/words-and-their-stories-green-means-spring/8001669.html',
    articleUrl: 'https://learningenglish.voanews.com/a/words-and-their-stories-green-idioim-expressions-garden-jealousy/2688277.html',
    en: [
      'Now, the VOA Learning English program Words and Their Stories. Today we talk about a color found all throughout nature – green! Green is also very common in American English. Let\u2019s hear Warren Scheer read a story about these colorful expressions!',
      'Green is an important color in nature. It is the color of grass and the leaves on trees. It is also the color of most growing plants.',
      'Sometimes, the word green means young, fresh and growing. Sometimes, it describes something that is not yet ripe or finished.',
      'For example, a greenhorn is someone who has no experience, who is new to a situation. In the fifteenth century, a greenhorn was a young cow or ox whose horns had not yet developed. A century or so later, a greenhorn was a soldier who had not yet had any experience in battle. By the eighteenth century, a greenhorn had the meaning it has today — a person who is new in a job.',
      'Someone who has the ability to grow plants well is said to have a green thumb. The expression comes from the early 1900s. A person with a green thumb seems to have a magic touch that makes plants grow quickly and well.',
      'The Green Revolution is the name given some years ago to the development of new kinds of rice and other grains. The new plants produced much larger crops. The Green Revolution was the result of hard work by agricultural scientists who had green thumbs.',
      'Green is also the color used to describe the powerful emotion, jealousy. The green-eyed monster is not a frightening creature from outer space. It is an expression used about four hundred years ago by British writer William Shakespeare in his play \u201cOthello.\u201d',
      'It describes the unpleasant feeling a person has when someone has something he wants. A young man may suffer from the green-eyed monster if his girlfriend begins going out with someone else. Or, that green-eyed monster may affect your friend if you get a pay raise and she does not.',
      'In most places in the world, a green light is a sign to move ahead. A green light on a traffic signal means your car can continue on. In everyday speech, a green light means approval to continue with a project.',
      'And that\u2019s all the time we have for this Words and Their Stories. Don\u2019t forget to tune in again for another story about American English expressions. Until next time! I\u2019m Anna Matteo. Marilyn Christiano wrote this program. Warren Scheer and Anna Matteo narrated.',
    ],
    vi: [
      'Chương trình Words and Their Stories của VOA Learning English. Hôm nay chúng ta nói về một màu sắc có khắp nơi trong tự nhiên — màu xanh lá! Màu xanh cũng rất phổ biến trong tiếng Anh Mỹ. Cùng nghe Warren Scheer đọc một câu chuyện về những cách diễn đạt đầy màu sắc này!',
      'Màu xanh lá là một màu quan trọng trong tự nhiên. Đó là màu của cỏ và lá cây, cũng là màu của hầu hết cây đang sinh trưởng.',
      'Đôi khi, từ green mang nghĩa trẻ, tươi mới và đang phát triển. Đôi khi nó mô tả thứ gì đó chưa chín hoặc chưa hoàn thiện.',
      'Ví dụ, greenhorn là người không có kinh nghiệm, mới bước vào một tình huống. Vào thế kỷ 15, greenhorn là con bê non mà sừng chưa phát triển. Khoảng một thế kỷ sau, greenhorn là người lính chưa từng ra trận. Đến thế kỷ 18, greenhorn mang nghĩa như ngày nay — người mới vào nghề.',
      'Người trồng cây tốt được gọi là có green thumb (ngón tay cái xanh). Thành ngữ này có từ đầu những năm 1900. Người có green thumb dường như có phép màu làm cây lớn nhanh và tốt.',
      'Cách mạng Xanh (Green Revolution) là tên gọi cho sự phát triển các giống lúa và ngũ cốc mới từ nhiều năm trước. Các giống mới cho sản lượng lớn hơn nhiều. Đó là kết quả lao động miệt mài của các nhà khoa học nông nghiệp có green thumb.',
      'Màu xanh cũng được dùng để mô tả cảm xúc mạnh — sự ghen tị. Green-eyed monster không phải quái vật đáng sợ từ ngoài hành tinh. Đây là cách diễn đạt được nhà văn Anh William Shakespeare dùng khoảng 400 năm trước trong vở kịch \u201cOthello.\u201d',
      'Nó mô tả cảm giác khó chịu khi người khác có thứ mình muốn. Một chàng trai có thể bị green-eyed monster nếu bạn gái bắt đầu đi chơi với người khác. Hoặc nó có thể ảnh hưởng đến bạn nếu bạn được tăng lương còn cô bạn thì không.',
      'Ở hầu hết nơi trên thế giới, đèn xanh (green light) là tín hiệu được phép đi tiếp. Đèn xanh ở giao lộ nghĩa là xe bạn được phép chạy tiếp. Trong lời nói hằng ngày, green light nghĩa là được chấp thuận để tiếp tục một dự án.',
      'Và đó là toàn bộ thời gian của Words and Their Stories hôm nay. Đừng quên đón nghe câu chuyện mới về các thành ngữ tiếng Anh Mỹ. Hẹn gặp lại! Tôi là Anna Matteo. Marilyn Christiano viết chương trình này. Warren Scheer và Anna Matteo đọc.',
    ],
  },
  {
    id: 'watching-grass-grow',
    title: '\u2018Watching the Grass Grow\u2019 Is Not Fun',
    series: 'VOA Learning English — Words and Their Stories',
    date: '2025-03-11',
    level: 'Trung cấp',
    duration: '3:19',
    audioUrl: 'https://voa-audio.voanews.eu/vle/2025/03/11/08bbcb88-2304-42bd-0531-08dd5c8b1668_hq.mp3',
    audioPageUrl: 'https://learningenglish.voanews.com/a/watching-the-grass-grow-is-not-fun/8006750.html',
    articleUrl: 'https://learningenglish.voanews.com/a/watching-the-grass-grow-is-not-fun/8003108.html',
    en: [
      'And now Words and Their Stories from VOA Learning English. Springtime is a time of renewal and growth. Many plants end their long winter sleep and form new buds and shoots. Beautiful flowers will soon be showing their bright colors. And the grass will grow thicker and greener again.',
      'Some flowers bloom in a very noticeable way but that is not the case with grass. Imagine you are sitting in a grassy field. And you have only one job – to watch the grass grow. That does not sound very interesting. In fact, it sounds really boring.',
      'That idea is what gives us the expression \u201clike watching grass grow.\u201d We use this expression to describe an experience that is uninteresting. Another good word to describe it is tedious.',
      'We use this expression in many situations. Let\u2019s hear a few examples: After the politician won his campaign, he gave a two-hour long acceptance speech. Two hours! It was as much fun as watching grass grow. I really don\u2019t like watching long sports games. It\u2019s like watching grass grow.',
      'Now, grass grows on the ground all the time. And usually, we don\u2019t give it much thought. If you stand in one place for a long time, the grass will continue to grow under your feet.',
      'For people who are always active, always moving, always on-the-go, we can say they don\u2019t let grass grow under their feet. We can also say beneath their feet. And sometimes we use this expression as a command.',
      'Let\u2019s hear some examples: Don\u2019t let the grass grow beneath your feet. Get back to work. She certainly doesn\u2019t let the grass grow under her feet. She\u2019s been traveling non-stop for over a year.',
      'And that\u2019s all the time we have for this Words and Their Stories. Until next time, I\u2019m Anna Matteo. Anna Matteo wrote this story for VOA Learning English.',
    ],
    vi: [
      'Và bây giờ là Words and Their Stories từ VOA Learning English. Mùa xuân là thời điểm đổi mới và sinh trưởng. Nhiều cây kết thúc giấc ngủ đông dài và nhú chồi non, mầm mới. Những bông hoa đẹp sắp khoe sắc rực rỡ. Và cỏ sẽ lại dày và xanh hơn.',
      'Một số loài hoa nở rất nổi bật, nhưng cỏ thì không như vậy. Hãy tưởng tượng bạn ngồi giữa cánh đồng cỏ, và việc duy nhất của bạn là nhìn cỏ mọc. Nghe chẳng thú vị chút nào. Thật ra, nó rất chán.',
      'Ý tưởng đó tạo nên thành ngữ \u201clike watching grass grow\u201d (như ngồi nhìn cỏ mọc). Chúng ta dùng thành ngữ này để mô tả một trải nghiệm không thú vị. Một từ hay khác để diễn tả là tedious (tẻ nhạt, dài dòng).',
      'Chúng ta dùng thành ngữ này trong nhiều tình huống. Cùng nghe vài ví dụ: Sau khi thắng cử, chính trị gia đó đọc bài diễn văn nhậm chức dài hai tiếng đồng hồ. Hai tiếng! Chán như ngồi nhìn cỏ mọc. Tôi thật sự không thích xem các trận thể thao dài. Nó như ngồi nhìn cỏ mọc.',
      'Cỏ mọc trên mặt đất suốt ngày, và thường chúng ta chẳng để tâm đến. Nếu bạn đứng yên một chỗ thật lâu, cỏ vẫn tiếp tục mọc dưới chân bạn.',
      'Với những người luôn năng động, luôn di chuyển, luôn bận rộn (on-the-go), ta có thể nói họ không để cỏ mọc dưới chân (don\u2019t let grass grow under their feet). Ta cũng có thể nói beneath their feet. Và đôi khi thành ngữ này được dùng như một mệnh lệnh.',
      'Cùng nghe vài ví dụ: Đừng để cỏ mọc dưới chân. Quay lại làm việc đi. Cô ấy chắc chắn không để cỏ mọc dưới chân mình. Cô ấy đã đi không ngừng nghỉ hơn một năm.',
      'Và đó là toàn bộ thời gian của Words and Their Stories hôm nay. Hẹn gặp lại, tôi là Anna Matteo. Anna Matteo viết câu chuyện này cho VOA Learning English.',
    ],
  },
];
