// Nội dung Podcast — bài nghe VOA Learning English (public domain, hợp pháp)
// Transcript EN lấy nguyên văn từ trang bài viết của VOA; phần dịch VI do chúng tôi biên soạn.
// Muốn thêm bài: copy 1 object mẫu, điền audioUrl (lấy nút "Direct link" trên trang
// episode của VOA) + en/vi transcript tương ứng.

export const YOUTUBE_CHANNELS = [
  {
    id: "bbc-learning-english",
    name: "BBC Learning English",
    handle: "@bbclearningenglish",
    url: "https://www.youtube.com/@bbclearningenglish",
    description: "Kênh chính thức BBC — 6 Minute English, The English We Speak, News Review.",
    color: "#7c0b0b",
  },
  {
    id: "voa-learning-english",
    name: "VOA Learning English",
    handle: "@VOALearningEnglish",
    url: "https://www.youtube.com/@VOALearningEnglish",
    description: "VOA — tin chậm, Words and Their Stories, Everyday Grammar TV.",
    color: "#0057b8",
  },
  {
    id: "english-with-lucy",
    name: "English with Lucy",
    handle: "@EnglishwithLucy",
    url: "https://www.youtube.com/@EnglishwithLucy",
    description: "Phát âm, từ vựng, ngữ pháp tiếng Anh thực dụng.",
    color: "#e8590c",
  },
  {
    id: "ted-ed",
    name: "TED-Ed",
    handle: "@TEDEd",
    url: "https://www.youtube.com/@TEDEd",
    description: "Video hoạt hình ngắn nhiều chủ đề — nghe hiểu học thuật.",
    color: "#e62b1e",
  },
  {
    id: "rachels-english",
    name: "Rachel's English",
    handle: "@rachelsenglish",
    url: "https://www.youtube.com/@rachelsenglish",
    description: "Luyện phát âm Anh-Mỹ chậm, rõ, chi tiết.",
    color: "#ad1457",
  },
];

export const PODCAST_LESSONS = [
  {
    id: "watching-grass-grow",
    title: "\u2018Watching the Grass Grow\u2019 Is Not Fun",
    series: "VOA Learning English — Words and Their Stories",
    date: "2025-03-11",
    level: "Trung cấp",
    duration: "3:19",
    audioUrl: "https://voa-audio.voanews.eu/vle/2025/03/11/08bbcb88-2304-42bd-0531-08dd5c8b1668_hq.mp3",
    audioPageUrl: "https://learningenglish.voanews.com/a/watching-the-grass-grow-is-not-fun/8006750.html",
    articleUrl: "https://learningenglish.voanews.com/a/watching-the-grass-grow-is-not-fun/8003108.html",
    en: [
      "And now Words and Their Stories from VOA Learning English. Springtime is a time of renewal and growth. Many plants end their long winter sleep and form new buds and shoots. Beautiful flowers will soon be showing their bright colors. And the grass will grow thicker and greener again.",
      "Some flowers bloom in a very noticeable way but that is not the case with grass. Imagine you are sitting in a grassy field. And you have only one job – to watch the grass grow. That does not sound very interesting. In fact, it sounds really boring.",
      "That idea is what gives us the expression \u201clike watching grass grow.\u201d We use this expression to describe an experience that is uninteresting. Another good word to describe it is tedious.",
      "We use this expression in many situations. Let\u2019s hear a few examples: After the politician won his campaign, he gave a two-hour long acceptance speech. Two hours! It was as much fun as watching grass grow. I really don\u2019t like watching long sports games. It\u2019s like watching grass grow.",
      "Now, grass grows on the ground all the time. And usually, we don\u2019t give it much thought. If you stand in one place for a long time, the grass will continue to grow under your feet.",
      "For people who are always active, always moving, always on-the-go, we can say they don\u2019t let grass grow under their feet. We can also say beneath their feet. And sometimes we use this expression as a command.",
      "Let\u2019s hear some examples: Don\u2019t let the grass grow beneath your feet. Get back to work. She certainly doesn\u2019t let the grass grow under her feet. She\u2019s been traveling non-stop for over a year.",
      "And that\u2019s all the time we have for this Words and Their Stories. Until next time, I\u2019m Anna Matteo. Anna Matteo wrote this story for VOA Learning English.",
    ],
    vi: [
      "Và bây giờ là Words and Their Stories từ VOA Learning English. Mùa xuân là thời điểm đổi mới và sinh trưởng. Nhiều cây kết thúc giấc ngủ đông dài và nhú chồi non, mầm mới. Những bông hoa đẹp sắp khoe sắc rực rỡ. Và cỏ sẽ lại dày và xanh hơn.",
      "Một số loài hoa nở rất nổi bật, nhưng cỏ thì không như vậy. Hãy tưởng tượng bạn ngồi giữa cánh đồng cỏ, và việc duy nhất của bạn là nhìn cỏ mọc. Nghe chẳng thú vị chút nào. Thật ra, nó rất chán.",
      "Ý tưởng đó tạo nên thành ngữ \u201clike watching grass grow\u201d (như ngồi nhìn cỏ mọc). Chúng ta dùng thành ngữ này để mô tả một trải nghiệm không thú vị. Một từ hay khác để diễn tả là tedious (tẻ nhạt, dài dòng).",
      "Chúng ta dùng thành ngữ này trong nhiều tình huống. Cùng nghe vài ví dụ: Sau khi thắng cử, chính trị gia đó đọc bài diễn văn nhậm chức dài hai tiếng đồng hồ. Hai tiếng! Chán như ngồi nhìn cỏ mọc. Tôi thật sự không thích xem các trận thể thao dài. Nó như ngồi nhìn cỏ mọc.",
      "Cỏ mọc trên mặt đất suốt ngày, và thường chúng ta chẳng để tâm đến. Nếu bạn đứng yên một chỗ thật lâu, cỏ vẫn tiếp tục mọc dưới chân bạn.",
      "Với những người luôn năng động, luôn di chuyển, luôn bận rộn (on-the-go), ta có thể nói họ không để cỏ mọc dưới chân (don\u2019t let grass grow under their feet). Ta cũng có thể nói beneath their feet. Và đôi khi thành ngữ này được dùng như một mệnh lệnh.",
      "Cùng nghe vài ví dụ: Đừng để cỏ mọc dưới chân. Quay lại làm việc đi. Cô ấy chắc chắn không để cỏ mọc dưới chân mình. Cô ấy đã đi không ngừng nghỉ hơn một năm.",
      "Và đó là toàn bộ thời gian của Words and Their Stories hôm nay. Hẹn gặp lại, tôi là Anna Matteo. Anna Matteo viết câu chuyện này cho VOA Learning English.",
    ],
  },
  {
    id: "green-means-spring",
    title: "Green Means Spring and Other Things",
    series: "VOA Learning English — Words and Their Stories",
    date: "2025-03-07",
    level: "Trung cấp",
    duration: "5:14",
    audioUrl: "https://voa-audio.voanews.eu/vle/2025/03/06/323d1873-affa-4fac-2d98-08dd5c897904_hq.mp3",
    audioPageUrl: "https://learningenglish.voanews.com/a/words-and-their-stories-green-means-spring/8001669.html",
    articleUrl: "https://learningenglish.voanews.com/a/words-and-their-stories-green-idioim-expressions-garden-jealousy/2688277.html",
    en: [
      "Now, the VOA Learning English program Words and Their Stories. Today we talk about a color found all throughout nature – green! Green is also very common in American English. Let\u2019s hear Warren Scheer read a story about these colorful expressions!",
      "Green is an important color in nature. It is the color of grass and the leaves on trees. It is also the color of most growing plants.",
      "Sometimes, the word green means young, fresh and growing. Sometimes, it describes something that is not yet ripe or finished.",
      "For example, a greenhorn is someone who has no experience, who is new to a situation. In the fifteenth century, a greenhorn was a young cow or ox whose horns had not yet developed. A century or so later, a greenhorn was a soldier who had not yet had any experience in battle. By the eighteenth century, a greenhorn had the meaning it has today — a person who is new in a job.",
      "Someone who has the ability to grow plants well is said to have a green thumb. The expression comes from the early 1900s. A person with a green thumb seems to have a magic touch that makes plants grow quickly and well.",
      "The Green Revolution is the name given some years ago to the development of new kinds of rice and other grains. The new plants produced much larger crops. The Green Revolution was the result of hard work by agricultural scientists who had green thumbs.",
      "Green is also the color used to describe the powerful emotion, jealousy. The green-eyed monster is not a frightening creature from outer space. It is an expression used about four hundred years ago by British writer William Shakespeare in his play \u201cOthello.\u201d",
      "It describes the unpleasant feeling a person has when someone has something he wants. A young man may suffer from the green-eyed monster if his girlfriend begins going out with someone else. Or, that green-eyed monster may affect your friend if you get a pay raise and she does not.",
      "In most places in the world, a green light is a sign to move ahead. A green light on a traffic signal means your car can continue on. In everyday speech, a green light means approval to continue with a project.",
      "And that\u2019s all the time we have for this Words and Their Stories. Don\u2019t forget to tune in again for another story about American English expressions. Until next time! I\u2019m Anna Matteo. Marilyn Christiano wrote this program. Warren Scheer and Anna Matteo narrated.",
    ],
    vi: [
      "Chương trình Words and Their Stories của VOA Learning English. Hôm nay chúng ta nói về một màu sắc có khắp nơi trong tự nhiên — màu xanh lá! Màu xanh cũng rất phổ biến trong tiếng Anh Mỹ. Cùng nghe Warren Scheer đọc một câu chuyện về những cách diễn đạt đầy màu sắc này!",
      "Màu xanh lá là một màu quan trọng trong tự nhiên. Đó là màu của cỏ và lá cây, cũng là màu của hầu hết cây đang sinh trưởng.",
      "Đôi khi, từ green mang nghĩa trẻ, tươi mới và đang phát triển. Đôi khi nó mô tả thứ gì đó chưa chín hoặc chưa hoàn thiện.",
      "Ví dụ, greenhorn là người không có kinh nghiệm, mới bước vào một tình huống. Vào thế kỷ 15, greenhorn là con bê non mà sừng chưa phát triển. Khoảng một thế kỷ sau, greenhorn là người lính chưa từng ra trận. Đến thế kỷ 18, greenhorn mang nghĩa như ngày nay — người mới vào nghề.",
      "Người trồng cây tốt được gọi là có green thumb (ngón tay cái xanh). Thành ngữ này có từ đầu những năm 1900. Người có green thumb dường như có phép màu làm cây lớn nhanh và tốt.",
      "Cách mạng Xanh (Green Revolution) là tên gọi cho sự phát triển các giống lúa và ngũ cốc mới từ nhiều năm trước. Các giống mới cho sản lượng lớn hơn nhiều. Đó là kết quả lao động miệt mài của các nhà khoa học nông nghiệp có green thumb.",
      "Màu xanh cũng được dùng để mô tả cảm xúc mạnh — sự ghen tị. Green-eyed monster không phải quái vật đáng sợ từ ngoài hành tinh. Đây là cách diễn đạt được nhà văn Anh William Shakespeare dùng khoảng 400 năm trước trong vở kịch \u201cOthello.\u201d",
      "Nó mô tả cảm giác khó chịu khi người khác có thứ mình muốn. Một chàng trai có thể bị green-eyed monster nếu bạn gái bắt đầu đi chơi với người khác. Hoặc nó có thể ảnh hưởng đến bạn nếu bạn được tăng lương còn cô bạn thì không.",
      "Ở hầu hết nơi trên thế giới, đèn xanh (green light) là tín hiệu được phép đi tiếp. Đèn xanh ở giao lộ nghĩa là xe bạn được phép chạy tiếp. Trong lời nói hằng ngày, green light nghĩa là được chấp thuận để tiếp tục một dự án.",
      "Và đó là toàn bộ thời gian của Words and Their Stories hôm nay. Đừng quên đón nghe câu chuyện mới về các thành ngữ tiếng Anh Mỹ. Hẹn gặp lại! Tôi là Anna Matteo. Marilyn Christiano viết chương trình này. Warren Scheer và Anna Matteo đọc.",
    ],
  },
  {
    id: "dish-up-something-good",
    title: "How to \u2018Dish Up\u2019 Something Good",
    series: "VOA Learning English — Words and Their Stories",
    date: "2025-02-27",
    level: "Trung cấp",
    duration: "3:41",
    audioUrl: "https://voa-audio.voanews.eu/vle/2025/02/27/88d03fae-92b2-4f86-902b-08dd4a843460_hq.mp3",
    audioPageUrl: "https://learningenglish.voanews.com/a/how-to-dish-up-something-good/7990601.html",
    articleUrl: "https://learningenglish.voanews.com/a/how-to-dish-up-something-good/7980848.html",
    en: [
      "And now, Words and Their Stories, from VOA Learning English. Food is a popular subject with many people around the world. It is fun to talk about our favorite dishes. It is even more fun to share a favorite dish with others.",
      "Today we talk about the word \u201cdish.\u201d A dish can be the object on which you serve food. But, a dish can also mean a specially prepared food.",
      "Do you have a signature dish? Our signature is how we sign our names. So, a signature dish is a dish we are known for making well. In a way, it identifies us.",
      "My signature dish is sweet potato rosemary dinner rolls. I am often asked to make them, especially for holiday parties. In my circle of friends, I am known for this dish. When the rolls are on the table, people know that I made them.",
      "A tasty dish is something that makes a table look good and inviting. Sometimes the same can be said about a person. Someone who is good-looking can be called a dish. While this usage might be a bit dated, it is still used.",
      "Now, let\u2019s talk about the verb \u201cdish.\u201d \u201cTo dish\u201d can mean to talk about private or personal information. It might be gossip. But I can also dish about myself. For example, a friend may ask me to dish about my new job.",
      "I could also use a phrasal verb form and say my friend want me to dish out all the interesting details.",
      "Now, to dish up something means to put food on a dish for someone to eat. However, it can also mean sharing personal details, our own and others. We can also dish out things, like jokes or even insults.",
      "Some people like to tease or insult. They can dish out jokes and insults all day long. But sometimes these same people do not like it if you do the same to them.",
      "We have a saying for just such people. We say, \u201cThey can dish it out, but they can\u2019t take it.\u201d They are able and willing to share harsh thoughts, criticisms, or insults about others, but they do not think they, themselves, deserve such treatment.",
      "And that\u2019s Words and Their Stories. Until next time, I\u2019m Anna Matteo. Anna Matteo wrote this story for VOA Learning English.",
    ],
    vi: [
      "Và bây giờ là Words and Their Stories từ VOA Learning English. Ẩm thực là chủ đề được yêu thích với nhiều người trên khắp thế giới. Nói về những món ăn khoái khẩu thật vui. Chia sẻ món ăn yêu thích với người khác còn vui hơn.",
      "Hôm nay chúng ta nói về từ dish. Dish có thể là cái đĩa dùng để đựng thức ăn. Nhưng dish cũng có thể là một món ăn được chế biến riêng.",
      "Bạn có món signature dish (món đặc trưng) không? Signature là chữ ký của chúng ta. Vậy món signature dish là món mà ta được biết đến là nấu giỏi. Theo một cách nào đó, nó nhận diện con người chúng ta.",
      "Món signature dish của tôi là bánh mì cuộn khoai lang hương hương thảo. Người ta thường nhờ tôi làm món này, nhất là trong các bữa tiệc ngày lễ. Trong nhóm bạn của tôi, tôi được biết đến với món này. Khi khay bánh lên bàn, ai cũng biết là do tôi làm.",
      "Một món ăn ngon khiến bàn tiệc thêm hấp dẫn và mời gọi. Đôi khi điều đó cũng áp dụng cho con người. Người ưa nhìn có thể được gọi là a dish. Dù cách dùng này hơi cũ, nó vẫn được dùng.",
      "Giờ hãy nói về động từ dish. To dish có thể là kể chuyện riêng tư, chuyện cá nhân. Nó có thể là chuyện phiếm (gossip). Nhưng tôi cũng có thể dish về chính mình. Ví dụ, một người bạn có thể nhờ tôi dish về công việc mới của tôi.",
      "Tôi cũng có thể dùng dạng cụm động từ và nói rằng bạn tôi muốn tôi dish out mọi chi tiết thú vị.",
      "Còn to dish up something nghĩa là bày thức ăn ra đĩa cho ai đó ăn. Tuy nhiên, nó cũng có thể là chia sẻ chi tiết cá nhân, của mình và của người khác. Ta cũng có thể dish out nhiều thứ, như chuyện cười hay thậm chí lời xúc phạm.",
      "Một số người thích trêu chọc (tease) hoặc xúc phạm. Họ có thể dish out chuyện cười và lời xúc phạm cả ngày. Nhưng đôi khi chính những người này lại không thích nếu bạn làm điều tương tự với họ.",
      "Chúng ta có câu nói dành cho những người như vậy: \u201cThey can dish it out, but they can\u2019t take it.\u201d (Họ nói được người khác nhưng lại không chịu được khi bị nói lại.) Họ sẵn sàng chia sẻ những suy nghĩ gay gắt (harsh), lời chỉ trích hay xúc phạm về người khác, nhưng lại không nghĩ bản thân mình đáng bị đối xử như vậy.",
      "Và đó là Words and Their Stories. Hẹn gặp lại, tôi là Anna Matteo. Anna Matteo viết câu chuyện này cho VOA Learning English.",
    ],
  },
  {
    id: "eagle-eyes",
    title: "Don\u2019t Miss a Thing With \u2018Eagle Eyes\u2019",
    series: "VOA Learning English — Words and Their Stories",
    date: "2025-02-13",
    level: "Trung cấp",
    duration: "5:50",
    audioUrl: "https://voa-audio.voanews.eu/vle/2025/02/13/28e1d0dd-e5a5-4e8e-832a-08dd4a843460.mp3",
    audioPageUrl: "https://learningenglish.voanews.com/a/don-t-miss-a-thing-with-eagle-eyes-/7973671.html",
    articleUrl: "https://learningenglish.voanews.com/a/don-t-miss-a-thing-with-eagle-eyes-/7963085.html",
    en: [
      "And now, Words and Their Stories, from VOA Learning English. From above, birds must have a wonderful view of the world below. Flying over everything at such a height gives them a rare ability to see many things.",
      "In English, we use the term \u201cbird\u2019s eye view\u201d to describe a view from above as if seen by a bird in flight. It is also described as an \u201coverall view\u201d or \u201cbig picture view.\u201d",
      "For example, when I start a project, I first like to get a bird\u2019s eye view. I ask myself several important questions: What is the overall goal? Who is the main focus? What resources do I have available to me? Answers to these \u201cbig picture\u201d questions can help me understand the scope of the project.",
      "Now, let\u2019s talk about noticing the smaller details. Some birds, called raptors, are known for their extremely sharp vision. Eagles, hawks, and owls can see their prey from very far away.",
      "The Raptor Center is part of the University of Minnesota\u2019s College of Veterinary Medicine. Its website explains why eagles, hawks, and owls see so well: \u201cRaptors have powerful binocular vision, where both their left and right eyes can see and focus on a single object.\u201d",
      "Eagles and hawks also have a special bone structure around their eyes that protects them from bright sunlight. Their ability to focus on faraway details in addition to other factors make them extremely effective hunters.",
      "In English, the keen vision of eagles and hawks describes a certain type of person.",
      "If you have an eagle eye, you have the ability to see or notice distant objects. Also, you observe everything, even very small details which others might miss. On the same note, someone who is hawk-eyed watches and notices everything that happens.",
      "These types of people may even perceive things that are not clear to others. Both eagle-eyed and hawk-eyed people are observant or perceptive. A person does not have to have this ability all the time. They might use their keen vision and powers of observation only at certain times, especially times when they need to keep a close watch.",
      "For example, during Christmastime, hawk-eyed children might search the sky looking for Santa Claus. These children may not be very observant during the rest of the year, but during Christmastime, they are looking for gifts.",
      "Let\u2019s hear these terms used between two friends. A: This is a great party. Thanks for inviting me. B: The more the merrier! This yearly neighborhood party always draws a huge number of people. A: I\u2019d say so! There must be over a hundred people here! Hey, wait a minute. I think I see our old co-worker. Isn\u2019t that Samantha way over there by the food and drinks? B: I don\u2019t know. I can\u2019t see that far. A: It\u2019s her. My eagle eyes don\u2019t miss a thing. I\u2019m going to go say hi and grab the last hamburger while I\u2019m there. Oh, and you should let the hosts know that they\u2019re low on drinks. B: Wow! You\u2019re right. I didn\u2019t realize you were so hawk-eyed. A: Only at parties. I start off with a bird\u2019s eye view and then focus in on the food, drinks, and people I want to see more closely. See you in a few\u2026",
      "The term \u201ceagle eye\u201d has been used for hundreds of years. Word experts say it was first used in writing in the mid-1500s. The Oxford English Dictionary website says the \u201cearliest evidence for \u2018eagle eye\u2019 is from 1567, in the writing of Thomas Stapleton, a Roman Catholic theologian.\u201d A theologian is an expert in religious thought.",
      "And that\u2019s all the time we have for this Words and Their Stories. Until next time, I\u2019m Anna Matteo. Anna Matteo wrote this story for VOA Learning English.",
    ],
    vi: [
      "Và bây giờ là Words and Their Stories từ VOA Learning English. Từ trên cao, loài chim hẳn có một tầm nhìn (view) tuyệt vời về thế giới bên dưới. Bay lướt trên mọi thứ ở độ cao như vậy cho chúng khả năng hiếm có là thấy được rất nhiều thứ.",
      "Trong tiếng Anh, chúng ta dùng cụm bird\u2019s eye view (góc nhìn từ trên cao) để mô tả tầm nhìn từ trên xuống như được thấy bởi một con chim đang bay. Nó cũng được mô tả là \u201ccái nhìn tổng thể\u201d hay \u201cbức tranh lớn\u201d.",
      "Ví dụ, khi bắt đầu một dự án, trước tiên tôi thích có cái nhìn tổng thể. Tôi tự hỏi mình vài câu quan trọng: Mục tiêu chung là gì? Trọng tâm (focus) chính là ai? Tôi có sẵn những nguồn lực nào? Câu trả lời cho những câu hỏi \u201cbức tranh lớn\u201d này giúp tôi hiểu được phạm vi (scope) của dự án.",
      "Giờ hãy nói về việc chú ý (notice) những chi tiết nhỏ hơn. Một số loài chim gọi là raptor (chim săn mồi) nổi tiếng với thị lực cực sắc. Đại bàng, diều hâu và cú có thể nhìn thấy con mồi (prey) từ rất xa.",
      "Trung tâm Raptor thuộc trường Thú y của Đại học Minnesota. Trang web của trung tâm giải thích vì sao đại bàng, diều hâu và cú nhìn tốt đến vậy: \u201cChim săn mồi có thị lực hai mắt (binocular) mạnh, khi cả mắt trái và mắt phải cùng nhìn và hội tụ vào một vật thể duy nhất.\u201d",
      "Đại bàng và diều hâu còn có cấu trúc xương đặc biệt quanh mắt bảo vệ chúng khỏi ánh nắng chói. Khả năng tập trung vào chi tiết ở xa cùng các yếu tố (factor) khác khiến chúng trở thành thợ săn cực hiệu quả.",
      "Trong tiếng Anh, thị lực sắc bén (keen) của đại bàng và diều hâu dùng để mô tả một kiểu người nhất định.",
      "Nếu bạn có eagle eye (mắt đại bàng), bạn có khả năng nhìn hoặc nhận ra vật ở xa. Bạn cũng quan sát mọi thứ, kể cả chi tiết rất nhỏ mà người khác có thể bỏ lỡ. Tương tự, người hawk-eyed (mắt diều hâu) theo dõi và nhận ra mọi chuyện diễn ra.",
      "Những người này thậm chí có thể nhận thức (perceive) được điều chưa rõ với người khác. Cả người eagle-eyed và hawk-eyed đều tinh ý, nhạy bén. Một người không cần lúc nào cũng có khả năng này. Họ có thể chỉ dùng thị lực sắc bén và khả năng quan sát vào những lúc nhất định, đặc biệt khi cần theo dõi sát sao.",
      "Ví dụ, vào dịp Giáng sinh, những đứa trẻ hawk-eyed có thể ngước nhìn bầu trời tìm ông già Noel. Các em có thể không tinh ý lắm trong những ngày còn lại của năm, nhưng dịp Giáng sinh thì các em đang tìm quà.",
      "Cùng nghe hai người bạn dùng những cụm từ này. A: Bữa tiệc tuyệt quá. Cảm ơn cậu đã mời. B: Càng đông càng vui! Bữa tiệc khu phố hằng năm này luôn thu hút rất đông người. A: Tớ cũng nghĩ vậy! Ở đây chắc phải hơn một trăm người! Ơ, khoan đã. Tớ nghĩ tớ thấy đồng nghiệp cũ của chúng ta. Đằng kia là Samantha phải không, gần chỗ đồ ăn thức uống? B: Tớ không biết. Tớ không nhìn xa được thế. A: Là cô ấy đấy. Mắt đại bàng của tớ chẳng bỏ sót gì. Tớ qua chào rồi tranh thủ lấy luôn cái bánh hamburger cuối cùng. À, cậu nên báo chủ nhà là đồ uống sắp hết nhé. B: Chà! Cậu nói đúng. Tớ không nhận ra cậu hawk-eyed đến vậy. A: Chỉ ở tiệc tùng thôi. Tớ bắt đầu bằng cái nhìn tổng thể rồi tập trung vào đồ ăn, thức uống và những người tớ muốn gặp kỹ hơn. Lát gặp lại nhé\u2026",
      "Cụm eagle eye đã được dùng hàng trăm năm. Các chuyên gia ngôn ngữ cho rằng nó xuất hiện lần đầu trong văn bản vào giữa thế kỷ 16. Trang Oxford English Dictionary ghi \u201cbằng chứng sớm nhất cho \u2018eagle eye\u2019 là từ năm 1567, trong tác phẩm của Thomas Stapleton, một nhà thần học Công giáo.\u201d Nhà thần học là chuyên gia về tư tưởng tôn giáo.",
      "Và đó là toàn bộ thời gian của Words and Their Stories hôm nay. Hẹn gặp lại, tôi là Anna Matteo. Anna Matteo viết câu chuyện này cho VOA Learning English.",
    ],
  },
];
