// Nội dung Podcast — bài nghe VOA Learning English (public domain, hợp pháp)
// Mỗi bài là danh sách `lines`: câu tiếng Anh (đúng lời đọc trong audio) + bản dịch tiếng Việt
// của TỪNG câu. Thời điểm mỗi câu được tính tự động theo độ dài audio (xem PodcastPage.vue).
// Transcript EN lấy nguyên văn từ trang bài viết của VOA; phần dịch VI do chúng tôi biên soạn.

export const YOUTUBE_CHANNELS = [
  {
    id: "bbc-learning-english",
    name: "BBC Learning English",
    handle: "@bbclearningenglish",
    url: "https://www.youtube.com/@bbclearningenglish",
    description: "Kênh chính thức BBC — 6 Minute English, The English We Speak, News Review.",
    color: "#7c0b0b",
  },
  {
    id: "voa-learning-english",
    name: "VOA Learning English",
    handle: "@VOALearningEnglish",
    url: "https://www.youtube.com/@VOALearningEnglish",
    description: "VOA — tin chậm, Words and Their Stories, Everyday Grammar TV.",
    color: "#0057b8",
  },
  {
    id: "english-with-lucy",
    name: "English with Lucy",
    handle: "@EnglishwithLucy",
    url: "https://www.youtube.com/@EnglishwithLucy",
    description: "Phát âm, từ vựng, ngữ pháp tiếng Anh thực dụng.",
    color: "#e8590c",
  },
  {
    id: "ted-ed",
    name: "TED-Ed",
    handle: "@TEDEd",
    url: "https://www.youtube.com/@TEDEd",
    description: "Video hoạt hình ngắn nhiều chủ đề — nghe hiểu học thuật.",
    color: "#e62b1e",
  },
  {
    id: "rachels-english",
    name: "Rachel's English",
    handle: "@rachelsenglish",
    url: "https://www.youtube.com/@rachelsenglish",
    description: "Luyện phát âm Anh-Mỹ chậm, rõ, chi tiết.",
    color: "#ad1457",
  },
];

export const PODCAST_LESSONS = [
  {
    id: "watching-grass-grow",
    title: "\u2018Watching the Grass Grow\u2019 Is Not Fun",
    series: "VOA Learning English — Words and Their Stories",
    date: "2025-03-11",
    level: "Trung cấp",
    duration: "3:19",
    audioUrl: "https://voa-audio.voanews.eu/vle/2025/03/11/08bbcb88-2304-42bd-0531-08dd5c8b1668_hq.mp3",
    audioPageUrl: "https://learningenglish.voanews.com/a/watching-the-grass-grow-is-not-fun/8006750.html",
    articleUrl: "https://learningenglish.voanews.com/a/watching-the-grass-grow-is-not-fun/8003108.html",
    lines: [
      { en: "And now Words and Their Stories from VOA Learning English.", vi: "Và bây giờ là Words and Their Stories từ VOA Learning English." },
      { en: "Springtime is a time of renewal and growth.", vi: "Mùa xuân là thời điểm đổi mới và sinh trưởng." },
      { en: "Many plants end their long winter sleep and form new buds and shoots.", vi: "Nhiều cây kết thúc giấc ngủ đông dài và nhú chồi non, mầm mới." },
      { en: "Beautiful flowers will soon be showing their bright colors.", vi: "Những bông hoa đẹp sẽ sớm khoe sắc rực rỡ." },
      { en: "And the grass will grow thicker and greener again.", vi: "Và cỏ sẽ lại mọc dày và xanh hơn." },
      { en: "Some flowers bloom in a very noticeable way but that is not the case with grass.", vi: "Một số loài hoa nở rất nổi bật, nhưng cỏ thì không như vậy." },
      { en: "Imagine you are sitting in a grassy field.", vi: "Hãy tưởng tượng bạn đang ngồi giữa một cánh đồng cỏ." },
      { en: "And you have only one job \u2013 to watch the grass grow.", vi: "Và việc duy nhất của bạn là nhìn cỏ mọc." },
      { en: "That does not sound very interesting.", vi: "Nghe chẳng thú vị chút nào." },
      { en: "In fact, it sounds really boring.", vi: "Thật ra, nó rất chán." },
      { en: "That idea is what gives us the expression \u201clike watching grass grow.\u201d", vi: "Ý tưởng đó tạo nên thành ngữ \u201clike watching grass grow\u201d (như ngồi nhìn cỏ mọc)." },
      { en: "We use this expression to describe an experience that is uninteresting.", vi: "Chúng ta dùng thành ngữ này để mô tả một trải nghiệm không thú vị." },
      { en: "Another good word to describe it is tedious.", vi: "Một từ hay khác để diễn tả là tedious (tẻ nhạt, dài dòng)." },
      { en: "We use this expression in many situations.", vi: "Chúng ta dùng thành ngữ này trong nhiều tình huống." },
      { en: "Let\u2019s hear a few examples:", vi: "Cùng nghe vài ví dụ:" },
      { en: "After the politician won his campaign, he gave a two-hour long acceptance speech.", vi: "Sau khi thắng cử, chính trị gia đó đọc bài diễn văn nhậm chức dài hai tiếng đồng hồ." },
      { en: "Two hours!", vi: "Hai tiếng!" },
      { en: "It was as much fun as watching grass grow.", vi: "Chán như ngồi nhìn cỏ mọc vậy." },
      { en: "I really don\u2019t like watching long sports games.", vi: "Tôi thật sự không thích xem các trận thể thao dài." },
      { en: "It\u2019s like watching grass grow.", vi: "Nó như ngồi nhìn cỏ mọc." },
      { en: "Now, grass grows on the ground all the time.", vi: "Cỏ mọc trên mặt đất suốt ngày." },
      { en: "And usually, we don\u2019t give it much thought.", vi: "Và thường chúng ta chẳng để tâm đến." },
      { en: "If you stand in one place for a long time, the grass will continue to grow under your feet.", vi: "Nếu bạn đứng yên một chỗ thật lâu, cỏ vẫn tiếp tục mọc dưới chân bạn." },
      { en: "For people who are always active, always moving, always on-the-go, we can say they don\u2019t let grass grow under their feet.", vi: "Với những người luôn năng động, luôn di chuyển, luôn bận rộn (on-the-go), ta nói họ không để cỏ mọc dưới chân." },
      { en: "We can also say beneath their feet.", vi: "Ta cũng có thể nói beneath their feet." },
      { en: "And sometimes we use this expression as a command.", vi: "Và đôi khi thành ngữ này được dùng như một mệnh lệnh." },
      { en: "Let\u2019s hear some examples:", vi: "Cùng nghe vài ví dụ:" },
      { en: "Don\u2019t let the grass grow beneath your feet.", vi: "Đừng để cỏ mọc dưới chân." },
      { en: "Get back to work.", vi: "Quay lại làm việc đi." },
      { en: "She certainly doesn\u2019t let the grass grow under her feet.", vi: "Cô ấy chắc chắn không để cỏ mọc dưới chân mình." },
      { en: "She\u2019s been traveling non-stop for over a year.", vi: "Cô ấy đã đi không ngừng nghỉ hơn một năm." },
      { en: "And that\u2019s all the time we have for this Words and Their Stories.", vi: "Và đó là toàn bộ thời gian của Words and Their Stories hôm nay." },
      { en: "Until next time, I\u2019m Anna Matteo.", vi: "Hẹn gặp lại, tôi là Anna Matteo." },
      { en: "Anna Matteo wrote this story for VOA Learning English.", vi: "Anna Matteo viết câu chuyện này cho VOA Learning English." },
    ],
  },
  {
    id: "green-means-spring",
    title: "Green Means Spring and Other Things",
    series: "VOA Learning English — Words and Their Stories",
    date: "2025-03-07",
    level: "Trung cấp",
    duration: "5:14",
    audioUrl: "https://voa-audio.voanews.eu/vle/2025/03/06/323d1873-affa-4fac-2d98-08dd5c897904_hq.mp3",
    audioPageUrl: "https://learningenglish.voanews.com/a/words-and-their-stories-green-means-spring/8001669.html",
    articleUrl: "https://learningenglish.voanews.com/a/words-and-their-stories-green-idioim-expressions-garden-jealousy/2688277.html",
    lines: [
      { en: "Now, the VOA Learning English program Words and Their Stories.", vi: "Chương trình Words and Their Stories của VOA Learning English." },
      { en: "Today we talk about a color found all throughout nature \u2013 green!", vi: "Hôm nay chúng ta nói về một màu sắc có khắp nơi trong tự nhiên — màu xanh lá!" },
      { en: "Green is also very common in American English.", vi: "Màu xanh cũng rất phổ biến trong tiếng Anh Mỹ." },
      { en: "Let\u2019s hear Warren Scheer read a story about these colorful expressions!", vi: "Cùng nghe Warren Scheer đọc một câu chuyện về những cách diễn đạt đầy màu sắc này!" },
      { en: "Green is an important color in nature.", vi: "Màu xanh lá là một màu quan trọng trong tự nhiên." },
      { en: "It is the color of grass and the leaves on trees.", vi: "Đó là màu của cỏ và lá cây." },
      { en: "It is also the color of most growing plants.", vi: "Cũng là màu của hầu hết cây đang sinh trưởng." },
      { en: "Sometimes, the word green means young, fresh and growing.", vi: "Đôi khi, từ green mang nghĩa trẻ, tươi mới và đang phát triển." },
      { en: "Sometimes, it describes something that is not yet ripe or finished.", vi: "Đôi khi nó mô tả thứ gì đó chưa chín hoặc chưa hoàn thiện." },
      { en: "For example, a greenhorn is someone who has no experience, who is new to a situation.", vi: "Ví dụ, greenhorn là người không có kinh nghiệm, mới bước vào một tình huống." },
      { en: "In the fifteenth century, a greenhorn was a young cow or ox whose horns had not yet developed.", vi: "Vào thế kỷ 15, greenhorn là con bê non mà sừng chưa phát triển." },
      { en: "A century or so later, a greenhorn was a soldier who had not yet had any experience in battle.", vi: "Khoảng một thế kỷ sau, greenhorn là người lính chưa từng ra trận." },
      { en: "By the eighteenth century, a greenhorn had the meaning it has today \u2014 a person who is new in a job.", vi: "Đến thế kỷ 18, greenhorn mang nghĩa như ngày nay — người mới vào nghề." },
      { en: "Someone who has the ability to grow plants well is said to have a green thumb.", vi: "Người trồng cây tốt được gọi là có green thumb (ngón tay cái xanh)." },
      { en: "The expression comes from the early 1900s.", vi: "Thành ngữ này có từ đầu những năm 1900." },
      { en: "A person with a green thumb seems to have a magic touch that makes plants grow quickly and well.", vi: "Người có green thumb dường như có phép màu làm cây lớn nhanh và tốt." },
      { en: "The Green Revolution is the name given some years ago to the development of new kinds of rice and other grains.", vi: "Cách mạng Xanh (Green Revolution) là tên gọi cho sự phát triển các giống lúa và ngũ cốc mới từ nhiều năm trước." },
      { en: "The new plants produced much larger crops.", vi: "Các giống mới cho sản lượng lớn hơn nhiều." },
      { en: "The Green Revolution was the result of hard work by agricultural scientists who had green thumbs.", vi: "Đó là kết quả lao động miệt mài của các nhà khoa học nông nghiệp có green thumb." },
      { en: "Green is also the color used to describe the powerful emotion, jealousy.", vi: "Màu xanh cũng được dùng để mô tả cảm xúc mạnh — sự ghen tị." },
      { en: "The green-eyed monster is not a frightening creature from outer space.", vi: "Green-eyed monster không phải quái vật đáng sợ từ ngoài hành tinh." },
      { en: "It is an expression used about four hundred years ago by British writer William Shakespeare in his play \u201cOthello.\u201d", vi: "Đây là cách diễn đạt được nhà văn Anh William Shakespeare dùng khoảng 400 năm trước trong vở kịch \u201cOthello\u201d." },
      { en: "It describes the unpleasant feeling a person has when someone has something he wants.", vi: "Nó mô tả cảm giác khó chịu khi người khác có thứ mình muốn." },
      { en: "A young man may suffer from the green-eyed monster if his girlfriend begins going out with someone else.", vi: "Một chàng trai có thể bị green-eyed monster nếu bạn gái bắt đầu đi chơi với người khác." },
      { en: "Or, that green-eyed monster may affect your friend if you get a pay raise and she does not.", vi: "Hoặc nó có thể ảnh hưởng đến bạn nếu bạn được tăng lương còn cô bạn thì không." },
      { en: "In most places in the world, a green light is a sign to move ahead.", vi: "Ở hầu hết nơi trên thế giới, đèn xanh (green light) là tín hiệu được phép đi tiếp." },
      { en: "A green light on a traffic signal means your car can continue on.", vi: "Đèn xanh ở giao lộ nghĩa là xe bạn được phép chạy tiếp." },
      { en: "In everyday speech, a green light means approval to continue with a project.", vi: "Trong lời nói hằng ngày, green light nghĩa là được chấp thuận để tiếp tục một dự án." },
      { en: "And that\u2019s all the time we have for this Words and Their Stories.", vi: "Và đó là toàn bộ thời gian của Words and Their Stories hôm nay." },
      { en: "Don\u2019t forget to tune in again for another story about American English expressions.", vi: "Đừng quên đón nghe câu chuyện mới về các thành ngữ tiếng Anh Mỹ." },
      { en: "Until next time!", vi: "Hẹn gặp lại!" },
      { en: "I\u2019m Anna Matteo.", vi: "Tôi là Anna Matteo." },
      { en: "Marilyn Christiano wrote this program.", vi: "Marilyn Christiano viết chương trình này." },
      { en: "Warren Scheer and Anna Matteo narrated.", vi: "Warren Scheer và Anna Matteo đọc." },
    ],
  },
  {
    id: "dish-up-something-good",
    title: "How to 'Dish Up' Something Good",
    series: "VOA Learning English — Words and Their Stories",
    date: "2025-02-27",
    level: "Trung cấp",
    duration: "3:41",
    audioUrl: "https://voa-audio.voanews.eu/vle/2025/02/27/88d03fae-92b2-4f86-902b-08dd4a843460_hq.mp3",
    audioPageUrl: "https://learningenglish.voanews.com/a/how-to-dish-up-something-good/7990601.html",
    articleUrl: "https://learningenglish.voanews.com/a/how-to-dish-up-something-good/7980848.html",
    lines: [
      { en: "And now, Words and Their Stories, from VOA Learning English.", vi: "Và bây giờ là Words and Their Stories từ VOA Learning English." },
      { en: "Food is a popular subject with many people around the world.", vi: "Ẩm thực là chủ đề được yêu thích với nhiều người trên khắp thế giới." },
      { en: "It is fun to talk about our favorite dishes.", vi: "Nói về những món ăn khoái khẩu thật vui." },
      { en: "It is even more fun to share a favorite dish with others.", vi: "Chia sẻ món ăn yêu thích với người khác còn vui hơn." },
      { en: "Today we talk about the word dish.", vi: "Hôm nay chúng ta nói về từ dish." },
      { en: "A dish can be the object on which you serve food.", vi: "Dish có thể là cái đĩa dùng để đựng thức ăn." },
      { en: "But, a dish can also mean a specially prepared food.", vi: "Nhưng dish cũng có thể là một món ăn được chế biến riêng." },
      { en: "Do you have a signature dish?", vi: "Bạn có món signature dish (món đặc trưng) không?" },
      { en: "Our signature is how we sign our names.", vi: "Signature là chữ ký của chúng ta." },
      { en: "So, a signature dish is a dish we are known for making well.", vi: "Vậy món signature dish là món mà ta được biết đến là nấu giỏi." },
      { en: "In a way, it identifies us.", vi: "Theo một cách nào đó, nó nhận diện con người chúng ta." },
      { en: "My signature dish is sweet potato rosemary dinner rolls.", vi: "Món signature dish của tôi là bánh mì cuộn khoai lang hương hương thảo." },
      { en: "I am often asked to make them, especially for holiday parties.", vi: "Người ta thường nhờ tôi làm món này, nhất là trong các bữa tiệc ngày lễ." },
      { en: "In my circle of friends, I am known for this dish.", vi: "Trong nhóm bạn của tôi, tôi được biết đến với món này." },
      { en: "When the rolls are on the table, people know that I made them.", vi: "Khi khay bánh lên bàn, ai cũng biết là do tôi làm." },
      { en: "A tasty dish is something that makes a table look good and inviting.", vi: "Một món ăn ngon khiến bàn tiệc thêm hấp dẫn và mời gọi." },
      { en: "Sometimes the same can be said about a person.", vi: "Đôi khi điều đó cũng áp dụng cho con người." },
      { en: "Someone who is good-looking can be called a dish.", vi: "Người ưa nhìn có thể được gọi là a dish." },
      { en: "While this usage might be a bit dated, it is still used.", vi: "Dù cách dùng này hơi cũ, nó vẫn được dùng." },
      { en: "Now, let\u2019s talk about the verb dish.", vi: "Giờ hãy nói về động từ dish." },
      { en: "To dish can mean to talk about private or personal information.", vi: "To dish có thể là kể chuyện riêng tư, chuyện cá nhân." },
      { en: "It might be gossip.", vi: "Nó có thể là chuyện phiếm (gossip)." },
      { en: "But I can also dish about myself.", vi: "Nhưng tôi cũng có thể dish về chính mình." },
      { en: "For example, a friend may ask me to dish about my new job.", vi: "Ví dụ, một người bạn có thể nhờ tôi dish về công việc mới của tôi." },
      { en: "I could also use a phrasal verb form and say my friend want me to dish out all the interesting details.", vi: "Tôi cũng có thể dùng dạng cụm động từ và nói rằng bạn tôi muốn tôi dish out mọi chi tiết thú vị." },
      { en: "Now, to dish up something means to put food on a dish for someone to eat.", vi: "Còn to dish up something nghĩa là bày thức ăn ra đĩa cho ai đó ăn." },
      { en: "However, it can also mean sharing personal details, our own and others.", vi: "Tuy nhiên, nó cũng có thể là chia sẻ chi tiết cá nhân, của mình và của người khác." },
      { en: "We can also dish out things, like jokes or even insults.", vi: "Ta cũng có thể dish out nhiều thứ, như chuyện cười hay thậm chí lời xúc phạm." },
      { en: "Some people like to tease or insult.", vi: "Một số người thích trêu chọc (tease) hoặc xúc phạm." },
      { en: "They can dish out jokes and insults all day long.", vi: "Họ có thể dish out chuyện cười và lời xúc phạm cả ngày." },
      { en: "But sometimes these same people do not like it if you do the same to them.", vi: "Nhưng đôi khi chính những người này lại không thích nếu bạn làm điều tương tự với họ." },
      { en: "We have a saying for just such people.", vi: "Chúng ta có câu nói dành cho những người như vậy." },
      { en: "We say, they can dish it out, but they can\u2019t take it.", vi: "Chúng ta nói: they can dish it out, but they can\u2019t take it (nói được người khác nhưng không chịu được khi bị nói lại)." },
      { en: "They are able and willing to share harsh thoughts, criticisms, or insults about others, but they do not think they, themselves, deserve such treatment.", vi: "Họ sẵn sàng chia sẻ những suy nghĩ gay gắt (harsh), lời chỉ trích hay xúc phạm về người khác, nhưng lại không nghĩ bản thân mình đáng bị đối xử như vậy." },
      { en: "And that\u2019s Words and Their Stories.", vi: "Và đó là Words and Their Stories." },
      { en: "Until next time, I\u2019m Anna Matteo.", vi: "Hẹn gặp lại, tôi là Anna Matteo." },
      { en: "Anna Matteo wrote this story for VOA Learning English.", vi: "Anna Matteo viết câu chuyện này cho VOA Learning English." },
    ],
  },
  {
    id: "eagle-eyes",
    title: "Don't Miss a Thing With 'Eagle Eyes'",
    series: "VOA Learning English — Words and Their Stories",
    date: "2025-02-13",
    level: "Trung cấp",
    duration: "5:50",
    audioUrl: "https://voa-audio.voanews.eu/vle/2025/02/13/28e1d0dd-e5a5-4e8e-832a-08dd4a843460.mp3",
    audioPageUrl: "https://learningenglish.voanews.com/a/don-t-miss-a-thing-with-eagle-eyes-/7973671.html",
    articleUrl: "https://learningenglish.voanews.com/a/don-t-miss-a-thing-with-eagle-eyes-/7963085.html",
    lines: [
      { en: "And now, Words and Their Stories, from VOA Learning English.", vi: "Và bây giờ là Words and Their Stories từ VOA Learning English." },
      { en: "From above, birds must have a wonderful view of the world below.", vi: "Từ trên cao, loài chim hẳn có một tầm nhìn (view) tuyệt vời về thế giới bên dưới." },
      { en: "Flying over everything at such a height gives them a rare ability to see many things.", vi: "Bay lướt trên mọi thứ ở độ cao như vậy cho chúng khả năng hiếm có là thấy được rất nhiều thứ." },
      { en: "In English, we use the term bird\u2019s eye view to describe a view from above as if seen by a bird in flight.", vi: "Trong tiếng Anh, chúng ta dùng cụm bird\u2019s eye view (góc nhìn từ trên cao) để mô tả tầm nhìn từ trên xuống như được thấy bởi một con chim đang bay." },
      { en: "It is also described as an overall view or big picture view.", vi: "Nó cũng được mô tả là cái nhìn tổng thể hay bức tranh lớn." },
      { en: "For example, when I start a project, I first like to get a bird\u2019s eye view.", vi: "Ví dụ, khi bắt đầu một dự án, trước tiên tôi thích có cái nhìn tổng thể." },
      { en: "I ask myself several important questions: What is the overall goal? Who is the main focus? What resources do I have available to me?", vi: "Tôi tự hỏi mình vài câu quan trọng: Mục tiêu chung là gì? Trọng tâm (focus) chính là ai? Tôi có sẵn những nguồn lực nào?" },
      { en: "Answers to these big picture questions can help me understand the scope of the project.", vi: "Câu trả lời cho những câu hỏi bức tranh lớn này giúp tôi hiểu được phạm vi (scope) của dự án." },
      { en: "Now, let\u2019s talk about noticing the smaller details.", vi: "Giờ hãy nói về việc chú ý (notice) những chi tiết nhỏ hơn." },
      { en: "Some birds, called raptors, are known for their extremely sharp vision.", vi: "Một số loài chim gọi là raptor (chim săn mồi) nổi tiếng với thị lực cực sắc." },
      { en: "Eagles, hawks, and owls can see their prey from very far away.", vi: "Đại bàng, diều hâu và cú có thể nhìn thấy con mồi (prey) từ rất xa." },
      { en: "The Raptor Center is part of the University of Minnesota\u2019s College of Veterinary Medicine.", vi: "Trung tâm Raptor thuộc trường Thú y của Đại học Minnesota." },
      { en: "Its website explains why eagles, hawks, and owls see so well: Raptors have powerful binocular vision, where both their left and right eyes can see and focus on a single object.", vi: "Trang web của trung tâm giải thích vì sao đại bàng, diều hâu và cú nhìn tốt đến vậy: Chim săn mồi có thị lực hai mắt (binocular) mạnh, khi cả mắt trái và mắt phải cùng nhìn và hội tụ vào một vật thể duy nhất." },
      { en: "Eagles and hawks also have a special bone structure around their eyes that protects them from bright sunlight.", vi: "Đại bàng và diều hâu còn có cấu trúc xương đặc biệt quanh mắt bảo vệ chúng khỏi ánh nắng chói." },
      { en: "Their ability to focus on faraway details in addition to other factors make them extremely effective hunters.", vi: "Khả năng tập trung vào chi tiết ở xa cùng các yếu tố (factor) khác khiến chúng trở thành thợ săn cực hiệu quả." },
      { en: "In English, the keen vision of eagles and hawks describes a certain type of person.", vi: "Trong tiếng Anh, thị lực sắc bén (keen) của đại bàng và diều hâu dùng để mô tả một kiểu người nhất định." },
      { en: "If you have an eagle eye, you have the ability to see or notice distant objects.", vi: "Nếu bạn có eagle eye (mắt đại bàng), bạn có khả năng nhìn hoặc nhận ra vật ở xa." },
      { en: "Also, you observe everything, even very small details which others might miss.", vi: "Bạn cũng quan sát mọi thứ, kể cả chi tiết rất nhỏ mà người khác có thể bỏ lỡ." },
      { en: "On the same note, someone who is hawk-eyed watches and notices everything that happens.", vi: "Tương tự, người hawk-eyed (mắt diều hâu) theo dõi và nhận ra mọi chuyện diễn ra." },
      { en: "These types of people may even perceive things that are not clear to others.", vi: "Những người này thậm chí có thể nhận thức (perceive) được điều chưa rõ với người khác." },
      { en: "Both eagle-eyed and hawk-eyed people are observant or perceptive.", vi: "Cả người eagle-eyed và hawk-eyed đều tinh ý, nhạy bén." },
      { en: "A person does not have to have this ability all the time.", vi: "Một người không cần lúc nào cũng có khả năng này." },
      { en: "They might use their keen vision and powers of observation only at certain times, especially times when they need to keep a close watch.", vi: "Họ có thể chỉ dùng thị lực sắc bén và khả năng quan sát vào những lúc nhất định, đặc biệt khi cần theo dõi sát sao." },
      { en: "For example, during Christmastime, hawk-eyed children might search the sky looking for Santa Claus.", vi: "Ví dụ, vào dịp Giáng sinh, những đứa trẻ hawk-eyed có thể ngước nhìn bầu trời tìm ông già Noel." },
      { en: "These children may not be very observant during the rest of the year, but during Christmastime, they are looking for gifts.", vi: "Các em có thể không tinh ý lắm trong những ngày còn lại của năm, nhưng dịp Giáng sinh thì các em đang tìm quà." },
      { en: "Let\u2019s hear these terms used between two friends.", vi: "Cùng nghe hai người bạn dùng những cụm từ này." },
      { en: "A: This is a great party. Thanks for inviting me.", vi: "A: Bữa tiệc tuyệt quá. Cảm ơn cậu đã mời." },
      { en: "B: The more the merrier! This yearly neighborhood party always draws a huge number of people.", vi: "B: Càng đông càng vui! Bữa tiệc khu phố hằng năm này luôn thu hút rất đông người." },
      { en: "A: I\u2019d say so! There must be over a hundred people here! Hey, wait a minute. I think I see our old co-worker. Isn\u2019t that Samantha way over there by the food and drinks?", vi: "A: Tớ cũng nghĩ vậy! Ở đây chắc phải hơn một trăm người! Ơ, khoan đã. Tớ nghĩ tớ thấy đồng nghiệp cũ của chúng ta. Đằng kia là Samantha phải không, gần chỗ đồ ăn thức uống?" },
      { en: "B: I don\u2019t know. I can\u2019t see that far.", vi: "B: Tớ không biết. Tớ không nhìn xa được thế." },
      { en: "A: It\u2019s her. My eagle eyes don\u2019t miss a thing. I\u2019m going to go say hi and grab the last hamburger while I\u2019m there. Oh, and you should let the hosts know that they\u2019re low on drinks.", vi: "A: Là cô ấy đấy. Mắt đại bàng của tớ chẳng bỏ sót gì. Tớ qua chào rồi tranh thủ lấy luôn cái bánh hamburger cuối cùng. À, cậu nên báo chủ nhà là đồ uống sắp hết nhé." },
      { en: "B: Wow! You\u2019re right. I didn\u2019t realize you were so hawk-eyed.", vi: "B: Chà! Cậu nói đúng. Tớ không nhận ra cậu hawk-eyed đến vậy." },
      { en: "A: Only at parties. I start off with a bird\u2019s eye view and then focus in on the food, drinks, and people I want to see more closely. See you in a few\u2026", vi: "A: Chỉ ở tiệc tùng thôi. Tớ bắt đầu bằng cái nhìn tổng thể rồi tập trung vào đồ ăn, thức uống và những người tớ muốn gặp kỹ hơn. Lát gặp lại nhé\u2026" },
      { en: "The term eagle eye has been used for hundreds of years.", vi: "Cụm eagle eye đã được dùng hàng trăm năm." },
      { en: "Word experts say it was first used in writing in the mid-1500s.", vi: "Các chuyên gia ngôn ngữ cho rằng nó xuất hiện lần đầu trong văn bản vào giữa thế kỷ 16." },
      { en: "The Oxford English Dictionary website says the earliest evidence for eagle eye is from 1567, in the writing of Thomas Stapleton, a Roman Catholic theologian.", vi: "Trang Oxford English Dictionary ghi bằng chứng sớm nhất cho eagle eye là từ năm 1567, trong tác phẩm của Thomas Stapleton, một nhà thần học Công giáo." },
      { en: "A theologian is an expert in religious thought.", vi: "Nhà thần học là chuyên gia về tư tưởng tôn giáo." },
      { en: "And that\u2019s all the time we have for this Words and Their Stories.", vi: "Và đó là toàn bộ thời gian của Words and Their Stories hôm nay." },
      { en: "Until next time, I\u2019m Anna Matteo.", vi: "Hẹn gặp lại, tôi là Anna Matteo." },
      { en: "Anna Matteo wrote this story for VOA Learning English.", vi: "Anna Matteo viết câu chuyện này cho VOA Learning English." },
    ],
  },
];
