export const PORTED_PAGES = [
  '/',
  '/ai/hub',
  '/java/hub',
  '/frontend/hub',
  '/cloud/hub',
  '/english/hub',
  '/english',
  '/learning-paths',
  '/interview',
  '/game-memory',
  '/game-scramble',
  '/game-speedquiz',
  '/exam',
  '/skill-tracker',
  '/sentence-practice',
];

export const PORTED_PAGE_LABELS = {
  '/': 'Trang chủ',
  '/ai/hub': 'Học AI',
  '/java/hub': 'Java',
  '/frontend/hub': 'Frontend',
  '/cloud/hub': 'AWS Cloud',
  '/english/hub': 'English',
  '/english': 'Học Tiếng Anh',
  '/learning-paths': 'Lộ trình học',
  '/interview': 'Phỏng vấn Backend',
  '/game-memory': 'Ghép cặp',
  '/game-scramble': 'Xếp chữ',
  '/game-speedquiz': 'Trắc nghiệm nhanh',
  '/exam': 'Thi Tiếng Anh',
  '/skill-tracker': 'Skill Tracker',
  '/sentence-practice': 'Luyện nói & Viết',
};
