export const PORTED_PAGES = [
  '/',
  '/ai',
  '/ai/agent',
  '/dashboard',
  '/java/hub',
  '/frontend/hub',
  '/frontend/frameworks',
  '/frontend/html-css',
  '/frontend/javascript',
  '/frontend/responsive',
  '/frontend/ui-interview',
  '/cloud',
  '/english/hub',
  '/english',
  '/learning-paths',
  '/interview',
  '/game-memory',
  '/game-scramble',
  '/game-speedquiz',
  '/exam',
  '/skill-tracker',
  '/sentence-practice',
  '/accelerator',
  '/salary-interview',
  '/code-learn',
  '/interview-english',
  '/bmad-agents',
  '/java/thuc-chien',
  '/java/spring-boot',
  '/java/backend',
];

export const PORTED_PAGE_LABELS = {
  '/': 'Trang chủ',
  '/ai': 'Học AI',
  '/ai/agent': 'AI Agent',
  '/java/hub': 'Java',
  '/frontend/hub': 'Frontend',
  '/frontend/frameworks': 'React / Vue / Angular',
  '/frontend/html-css': 'HTML & CSS',
  '/cloud': 'AWS Cloud',
  '/english/hub': 'English',
  '/english': 'Học Tiếng Anh',
  '/learning-paths': 'Lộ trình học',
  '/interview': 'Phỏng vấn Backend',
  '/game-memory': 'Ghép cặp',
  '/game-scramble': 'Xếp chữ',
  '/game-speedquiz': 'Trắc nghiệm nhanh',
  '/exam': 'Thi Tiếng Anh',
  '/skill-tracker': 'Skill Tracker',
  '/sentence-practice': 'Luyện nói & Viết',
  '/accelerator': 'Accelerator 30-Day',
  '/salary-interview': 'Phỏng vấn theo lương',
  '/code-learn': 'Học Code',
  '/interview-english': 'Interview English',
  '/bmad-agents': 'BMAD Agents',
  '/dashboard': 'Dashboard',
  '/java/thuc-chien': 'Thực chiến',
  '/java/spring-boot': 'Spring Boot',
  '/java/backend': 'Backend',
};
