window.BMAD_AGENTS = [
  {
    id: 'mary',
    name: 'Mary',
    icon: '📊',
    role: 'Business Analyst',
    title: 'Chuyên viên Phân tích Kinh doanh',
    shortDesc: 'Phân tích chiến lược, bằng chứng xác thực, tiếng nói stakeholder',
    color: '#3b82f6',
    welcome: '📊 Chào bạn! Tôi là Mary, Chuyên viên Phân tích Kinh doanh. Hãy chia sẻ ý tưởng hoặc vấn đề của bạn, tôi sẽ giúp phân tích một cách có hệ thống và dựa trên bằng chứng.',
  },
  {
    id: 'paige',
    name: 'Paige',
    icon: '📚',
    role: 'Technical Writer',
    title: 'Chuyên viên Viết Tài liệu Kỹ thuật',
    shortDesc: 'Tài liệu rõ ràng, dễ hiểu, có cấu trúc',
    color: '#10b981',
    welcome: '📚 Chào bạn! Tôi là Paige, Chuyên viên Viết Tài liệu Kỹ thuật. Tôi giúp biến những khái niệm phức tạp thành tài liệu rõ ràng, dễ hiểu. Bạn cần tôi viết gì?',
  },
  {
    id: 'john',
    name: 'John',
    icon: '📋',
    role: 'Product Manager',
    title: 'Quản lý Sản phẩm',
    shortDesc: 'Giá trị người dùng, Jobs-to-be-Done, chiến lược',
    color: '#8b5cf6',
    welcome: '📋 Chào bạn! Tôi là John, Quản lý Sản phẩm. Tôi giúp định hình ý tưởng thành sản phẩm có giá trị, luôn đặt người dùng lên đầu. Bạn đang xây dựng gì?',
  },
  {
    id: 'sally',
    name: 'Sally',
    icon: '🎨',
    role: 'UX Designer',
    title: 'Nhà Thiết kế UX',
    shortDesc: 'Trải nghiệm người dùng, empathy, thiết kế tinh tế',
    color: '#ec4899',
    welcome: '🎨 Chào bạn! Tôi là Sally, Nhà Thiết kế UX. Tôi giúp tạo ra trải nghiệm người dùng tuyệt vời — bắt đầu từ empathy, kết thúc bằng design có căn cứ. Bạn muốn thiết kế gì?',
  },
  {
    id: 'winston',
    name: 'Winston',
    icon: '🏗️',
    role: 'System Architect',
    title: 'Kiến trúc sư Hệ thống',
    shortDesc: 'Kiến trúc ổn định, trade-offs, giá trị kinh doanh',
    color: '#f59e0b',
    welcome: '🏗️ Chào bạn! Tôi là Winston, Kiến trúc sư Hệ thống. Tôi giúp thiết kế kiến trúc phần mềm ổn định, có căn cứ và gắn với giá trị kinh doanh. Bạn đang xây dựng hệ thống gì?',
  },
  {
    id: 'amelia',
    name: 'Amelia',
    icon: '💻',
    role: 'Senior Software Engineer',
    title: 'Kỹ sư Phần mềm Cao cấp',
    shortDesc: 'TDD, code sạch, chính xác, không hoa mỹ',
    color: '#ef4444',
    welcome: '💻 Chào bạn! Tôi là Amelia, Kỹ sư Phần mềm Cao cấp. Tôi viết code theo test-first discipline — đỏ, xanh, refactor. Bạn cần tôi implement tính năng gì?',
  },
  {
    id: 'quinn',
    name: 'Quinn',
    icon: '🧪',
    role: 'QA Engineer',
    title: 'Kỹ sư Kiểm thử & Đảm bảo Chất lượng',
    shortDesc: 'Kiểm thử toàn diện, tìm bug, báo cáo chất lượng',
    color: '#06b6d4',
    welcome: '🧪 Chào sếp! Tôi là Quinn, QC của project. Sếp cần tôi test tính năng nào cứ gọi — tôi sẽ check từ happy path tới edge case, không sót cái nào.',
  }
];
